### ISSUE TITLE
Mp3 Download?

### ISSUE THREAD

**Issue by solistahoe** [pgmichael/wavenet-for-chrome#1]
Pg, I love your work, it has been a blessing for me and my family, but it would be perfect if it had the "download as mp3" functionality. 

Anyways, cheers and thank you again.

**Comment by pgmichael** [comment]
Hi @solistahoe,
I'm glad my extension could be of service to you and your family!

I've updated the current context menu which should allow you to either read the selected text as usual or download it as an MP3 file.

The extensions should automatically update itself within the next few hours.

Cheers!

**Comment by SalNash** [comment]
Hello, Thank you for the excellent and handy extension. It is very beneficial.
It's been a month I notice I can't download the MP3 file that is longer than a paragraph (around 200 characters including space) but on reading it doesn’t have any problem. I deleted and installed it again, and it's still the same. Also, I increased word limitation on my console, but it didn't fix it either.
I have a few questions:

- I was wondering if you would have any suggestion to fix it.

- Is there any way to increase the limitation from 5000 to 10000 or unlimited?

- Do you have or know any extension that would work with GCP translate as well?

Again thank for your great work.

**Comment by pgmichael** [comment]
@SalNash I've never had this issue before and to be honest I'm not quite sure on what could cause it. Is there any error message prompted when trying to download the file?

Concerning the word limitation, it's a limit imposed by Google Cloud itself. You can read more about it [here](https://cloud.google.com/text-to-speech/quotas). I have an idea on how to bypass this, but I don't know when I'll come around and implement it.

I also don't know of any extension that would work with Cloud Translation as well, but it's an interesting use case nonetheless.

**Comment by SalNash** [comment]
I used to download MP3 file very fine but it's been for a month that when I select and hit download, I get no error code or anything, even it shows it downloaded something but the download message is empty and says, Failed - Network error. 

<img width="328" alt="Screen Shot 2019-03-30 at 1 06 51 PM" src="https://user-images.githubusercontent.com/44656429/55279929-b8efe600-52ec-11e9-886b-58beaee6b110.png">

I just installed it on Vivaldi and it works great but not on my Chrome, and Canary and Chromium.

I think I have to erase all G-Chromes and reinstall them but before I sign-in my G-accounts to restore the browsers, I should disable the settings. Something must be wrong with my G-Chromes' Settings.

About Translation API, I found this code but I don't know how to execute it, 

https://gist.github.com/mkahn5/e67d4fba142cedcd416239cb86ad7a5e#file-translate-client-py

Can you make an extension with it?

**Comment by pgmichael** [comment]
Unfortunately, implementing the code you send me wouldn't be as straightforward as one could expect and quite truthfully, I'm not interested in supporting this feature at the moment. But I do appreciate your interest in the extension 😄.
