### ISSUE TITLE
Keyboard shortcut for download option?

### ISSUE THREAD

**Issue by timonvanhasselt** [pgmichael/wavenet-for-chrome#10]
A keyboard shortcut for the Download option would be very helpful (control/command + shift + D)

**Comment by pgmichael** [comment]
Unfortunately `CTRL + SHIFT + D` is already a shortcut in Chrome. Having that said, I don't see why it couldn't be configured from the `chrome://extensions/shortcuts` page as on optional features.

Thanks for the feedback!

**Comment by timonvanhasselt** [comment]
Nice, I wasn't aware of the current shortcut option in extensions (thanks). It would be great to extend that feature indeed. I've already added Control + Shift + W now for the WaveNet settings ;)

**Comment by pgmichael** [comment]
With today's update (chrome generally updates the extension within 24 hour), Idownloading should be possible through a shortcut. Default keys are `CRTL+SHIFT+E`.

Cheers!
