### ISSUE TITLE
Google Cloud Speech-to-Text - Speech Recognition for Chrome.

### ISSUE THREAD

**Issue by jump1r** [pgmichael/wavenet-for-chrome#13]
Hello, thank you for the Wavenet plugin that you developed, it is very easy to use. I have a question, do you have any plans to develop the Google Speech to Text for Chrome plugin? Thank you very much.

**Comment by pgmichael** [comment]
Hi @jump1r,
I'm not quite sure I fully grasp your question. I try to improve it whenever I have some free time!

Cheers!
