### ISSUE TITLE
Mixed ffprobe outputs over last 2-3 weeks MP3 creation

### ISSUE THREAD

**Issue by mvrht6** [pgmichael/wavenet-for-chrome#14]
I have downloaded MP3s created from SSML for some projects to add to videos then create with ffmpeg. Has something changed over the last month? As the ffprobe outputs for each batch of work we did seems to have changed (3 times by the looks of it). This has lead to some videos created not playing properly on certain devices. 

Work done on 19th Jan, ffprobe output:

```
Input #0, wav, from 'download (65).mp3':
  Duration: 00:00:18.04, bitrate: 384 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 24000 Hz, 1 channels, s16, 384 kb/s
```

Work done on 23rd Jan, ffprobe output:
```
Input #0, wav, from 'download (0).mp3':
  Duration: 00:00:35.94, bitrate: 384 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 24000 Hz, 1 channels, s16, 384 kb/s
```

Work done on 31st Jan, ffprobe output:
```
Input #0, ogg, from 'download (0).mp3':
  Metadata:
    TLEN            : 37003
  Duration: 00:00:37.00, start: 0.000000, bitrate: 23 kb/s
    Stream #0:0: Audio: opus, 48000 Hz, mono, fltp
```

Running it today 19th Feb now brings another set of file attributes!

```
Input #0, mp3, from 'download (1).mp3':
  Duration: 00:00:25.30, start: 0.000000, bitrate: 32 kb/s
    Stream #0:0: Audio: mp3, 24000 Hz, mono, fltp, 32 kb/s
```

But BTW, this plugin is brilliant! Just a bit of an issue with using these with video creation (ffmpeg) for me.

PS - Just for additional reference, this is the output from a file in June 2019 I created via Google TTS in Node myself

```
Input #0, wav, from 'download.mp3':
  Duration: 00:00:33.06, bitrate: 384 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 24000 Hz, 1 channels, s16, 384 kb/s
```

**Comment by pgmichael** [comment]
Hi there,
To be honest I’m not very knowledgeable when it comes to audio encoding. In one of my recent updates, I changed to encoding to OGG opus which caused a lot of issues for many users therefore I changed it back to MP3.

The TLEN metadata was added in hopes of fixing #7, but it didn’t seem to be recognized for most.

I think I’ll just leave things as they are unless someone has a better idea.

Cheers!
