### ISSUE TITLE
Is it possible to add the "Audio device profile" option? Thank you.

### ISSUE THREAD

**Issue by jump1r** [pgmichael/wavenet-for-chrome#32]
![123](https://user-images.githubusercontent.com/12111290/99190532-fe06ab80-27a1-11eb-940e-d48276c3fd72.jpg)

**Comment by R2Pitou** [comment]
Second this. Currently, audio device profile is tiny and tinny speaker. If I could use the profile made for large speakers, the sound would be a million times less robotic.

I've tried to download and install the developer version of this, but everything is broken and deprecated... Any links to still active alternatives to this are most welcome. Wavenet voices develop and advance all the time. This hasn't in 2 years.

**Comment by pgmichael** [comment]
Version 12 is pending Google's review. This should be possible when it updates (~1 to 3 business days).

![image](https://github.com/pgmichael/wavenet-for-chrome/assets/7294504/3f5790ee-2705-4a89-b894-2f5d6c189689)
