### ISSUE TITLE
Add options for other audio formats

### ISSUE THREAD

**Issue by daffi7** [pgmichael/wavenet-for-chrome#36]
Google WaveNet produces the best results when choosing WAV as the output file format. Would it be possible to add an option selecting the output format? Would be much appreciated!

Kind regards,
Michael Smilauer

**Comment by pgmichael** [comment]
I'm doing a rolling deployment of a new version that will allow you to download and playback audio using either MP3, OGG or WAV. I'll close this issue as this should become available to you in the coming days.
