### ISSUE TITLE
Start speaking shortcut is not working in some URL

### ISSUE THREAD

**Issue by houcheng** [pgmichael/wavenet-for-chrome#46]
Please check this url: http://futurepress.github.io/epub.js/examples/scrolled.html
The "Start speaking" does not works after pressing the shortcut.
The speaking feature does actually works by the right menu.

**Comment by pgmichael** [comment]
Closing this issue; I've added to list of unsupported context https://github.com/pgmichael/wavenet-for-chrome/issues/16 (text on the webpage is inside an `iFrame`).
