### ISSUE TITLE
Voices missing for Nederlands / Dutch

### ISSUE THREAD

**Issue by tonyellow** [pgmichael/wavenet-for-chrome#5]
Your plugin is fantastic. The only thing missing are the voices missing for Netherlands/Dutch: Wavenet A/B/C/D etc. Would be awesome if you could add them!

**Comment by pgmichael** [comment]
Turns out google's official documentation was outdated and I was missing quite a lot of voices... I've added all the missing voices and your extension should update itself within a few hours.

Cheers!

**Comment by tonyellow** [comment]
You're the best
