### ISSUE TITLE
Increase quotas

### ISSUE THREAD

**Issue by jordatormo** [pgmichael/wavenet-for-chrome#68]
I am always getting the same message. Even though sentences are quite short.
***
Either `input.text` or `input.ssml` is longer than the limit of 5000 bytes. This limit is different from quotas. To fix, reduce the byte length of the characters in this request, or consider using the Long Audio API: https://cloud.google.com/text-to-speech/docs/create-audio-text-long-audio-synthesis.
****

I read the article on Google but I don't understand what I have to do.

How can I increase that limit??

On my API I see all this cuotas:

Count of requests for Neural2 voices per minute 
All requests per minute
Count of requests for Long Audio Synthesis per minute
Count of requests for querying Long Audio Synthesis operations per minute
Count of requests for Studio voices per minute

What is exactly the process??? Can anybody help me with this? Thanks!!

**Comment by pgmichael** [comment]
Not possible to read SSML over 5k bytes at the moment. You'll need to split it in multiple chunks. Something that I'm hoping to improve eventually.

**Comment by pgmichael** [comment]
I'm doing a rolling deployment of a new version that should split SSML when over 5000 bytes. I'll close this issue as this should become available to you in the coming days.
