### ISSUE TITLE
ssml not working as of ver 10 update

### ISSUE THREAD

**Issue by macewatson** [pgmichael/wavenet-for-chrome#71]
As of today 7/26/23 ssml is no longer working.

exsample 
`<speak>
<prosody pitch="low">Absolutely!</prosody> The power of the Horde is <emphasis>undeniable</emphasis>! For the Horde! 
</speak>`

**Comment by pgmichael** [comment]
Uh oh! Fixed in version 11.

Currently pending Google's review. You can expect an update as soon as it's approved (usually 1-3 business days).

![image](https://github.com/pgmichael/wavenet-for-chrome/assets/7294504/3287c890-45f3-401e-9842-c4fc83cb5c02)
