### ISSUE TITLE
SSML not working in sandbox

### ISSUE THREAD

**Issue by blazejp83** [pgmichael/wavenet-for-chrome#73]
Tried using Sandbox with SSML, unfortunately the tags are not recognized and are always read. Whether I use <script></script> or encode it like &lt;script&gt; it's always read out loud.

**Comment by pgmichael** [comment]
Seems to work on my end! What version are you using? Can you leave me an example of the SSML you're trying to synthesize? 

It need to start and end with `<speak>` tags. Ex:

```xml
<speak>
  <prosody pitch="low">Absolutely!</prosody> The power of the Horde is <emphasis>undeniable</emphasis>! For the Horde!  
</speak>
```

Surely some improvements can be made on detecting whether or not it's text or SSML though.

**Comment by pgmichael** [comment]
Closing for the moment.
