### ISSUE TITLE
Failed to synthesize text - new error experienced

### ISSUE THREAD

**Issue by k0diak** [pgmichael/wavenet-for-chrome#79]
"Trying to acquire 1 unit; currently 1500 units in use; maximum of 1500 units allowed. Server: /bns/jt/borg/jt/bns/cloud-ml-tts-composer/prod-standard-voice-global.tts-composer/4"

tried to use smaller text grouping, didn't help.

**Comment by superluig164** [comment]
Just got this too, it seems to be triggered by a phrase I was trying to read, but the error seems unrelated.  Hopefully this can be fixed soon.

**Comment by pgmichael** [comment]
I'm monitoring this error, but appears like a temporary issue on Google's end. Will report back if it seems re-occurring .

**Comment by k0diak** [comment]
It's working again - just did 60k characters
 
#tyvm

**Comment by pgmichael** [comment]
Awesome :)
