### ISSUE TITLE
New voices! (August 2019)

### ISSUE THREAD

**Issue by yucolabjames** [pgmichael/wavenet-for-chrome#8]
Looks like Google just announced some new voices and variants to existing languages. 

[Cloud Text-to-Speech expands its number of voices by nearly 70%, now covering 33 languages and variants](https://cloud.google.com/text-to-speech/docs/list-voices)
![cloud_text-to-speech_lang 0863101116301872 max-1800x1800](https://user-images.githubusercontent.com/40826198/63819333-8a4b6980-c977-11e9-86e8-1db883957ffa.png)

If I have some time this week I'll create PR for this. But am wondering if @pgmichael has thought of programmatically getting the voices instead? I wonder if there is any implications: https://cloud.google.com/text-to-speech/docs/list-voices

**Comment by pgmichael** [comment]
@yucolabjames That's awesome! Thanks for letting me know if this change.

I'm definitely going to retrieve the voices programmatically in the future, but it will have to wait a little; I've started migrating the codebase to TypeScript.

Cheers!

**Comment by pgmichael** [comment]
With tonight's update (chrome generally updates the extension within 24 hour), all the new voices will be added automatically!

Cheers!
