### ISSUE TITLE
saying please enable billing?

### ISSUE THREAD

**Issue by ShadowFrost3167** [pgmichael/wavenet-for-chrome#83]
This API method requires billing to be enabled. Please enable billing on project #58906374421 by visiting https://console.developers.google.com/billing/enable?project=58906374421 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry.

just bought this stuff and set it up like a month ago. any ideas on how to fix this issue?

**Comment by pgmichael** [comment]
Hello, can you make sure there is still a valid credit card on file inside the your GCP project and try with a newly generated API key? I haven't done any changes in months and it's still working on my end.
